name: synapse_environment
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - pytorch
  - matplotlib
  - scikit-learn=1.3.2
  - scikit-image=0.25.2
  - tqdm=4.67.1
  - pillow=11.2.1
  - h5py=3.13.0
  - ipython=8.17.2
  - joblib=1.5.0
  - numba=0.61.2
  - networkx=3.2.1
  - imageio=2.37.0
  - pip=23.3.2
  - pandas
  - scipy
  - numpy
  - torchvision
  
  - pip:
    - webknossos==2.1.0
    - wkw==1.1.24
    - wget==3.2
    - PIMS==0.7
    - pynndescent==0.5.13

# To create and activate the environment:
# conda env create -f environment.yaml
# conda activate synapse_environment 