name: synapse_environment
channels:
  - conda-forge
  - nodefaults
dependencies:
  - _openmp_mutex=4.5
  - alsa-lib=1.2.14
  - aom=3.9.1
  - asttokens=3.0.0
  - blosc=1.21.6
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.34.5
  - c-blosc2=2.17.1
  - ca-certificates=2025.4.26
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.4
  - charls=2.4.2
  - colorama=0.4.6
  - contourpy=1.3.2
  - cpython=3.10.17
  - cycler=0.12.1
  - cyrus-sasl=2.1.27
  - dav1d=1.2.1
  - dbus=1.13.6
  - decorator=5.2.1
  - double-conversion=3.3.1
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - expat=2.7.0
  - filelock=3.18.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.58.0
  - freetype=2.13.3
  - fsspec=2025.3.2
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - graphite2=1.3.13
  - h5py=3.13.0
  - harfbuzz=11.2.1
  - hdf5=1.14.6
  - icu=75.1
  - imagecodecs=2024.12.30
  - imageio=2.37.0
  - importlib-metadata=8.6.1
  - ipython=8.17.2
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.0
  - jxrlib=1.1
  - keyutils=1.6.1
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lazy-loader=0.4
  - lazy_loader=0.4
  - lcms2=2.17
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libabseil=20250127.1
  - libaec=1.1.3
  - libavif16=1.3.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang-cpp20.1=20.1.5
  - libclang13=20.1.5
  - libcups=2.3.3
  - libcurl=8.13.0
  - libde265=1.0.15
  - libdeflate=1.24
  - libdrm=2.4.124
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libev=4.33
  - libexpat=2.7.0
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgfortran=15.1.0
  - libgfortran5=15.1.0
  - libgl=1.7.0
  - libglib=2.84.1
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libheif=1.19.7
  - libhwloc=2.11.2
  - libhwy=1.2.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - libjxl=0.11.1
  - liblapack=3.9.0
  - libllvm20=20.1.5
  - liblzma=5.8.1
  - libnghttp2=1.64.0
  - libnsl=2.0.1
  - libntlm=1.8
  - libopengl=1.7.0
  - libpciaccess=0.18
  - libpng=1.6.47
  - libpq=17.5
  - libprotobuf=5.29.3
  - libsqlite=3.49.2
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libtiff=4.7.0
  - libtorch=2.6.0
  - libuuid=2.38.1
  - libuv=1.50.0
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.9.2
  - libxml2=2.13.8
  - libxslt=1.1.39
  - libzlib=1.3.1
  - libzopfli=1.0.3
  - llvm-openmp=20.1.5
  - llvmlite=0.44.0
  - lz4-c=1.10.0
  - markupsafe=3.0.2
  - matplotlib=3.10.3
  - matplotlib-base=3.10.3
  - matplotlib-inline=0.1.7
  - mkl=2024.2.2
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - munkres=1.1.4
  - ncurses=6.5
  - networkx=3.2.1
  - numba=0.61.2
  - openjpeg=2.5.3
  - openldap=2.6.9
  - openssl=3.5.0
  - optree=0.15.0
  - packaging=25.0
  - pandas=2.2.3
  - parso=0.8.4
  - pcre2=10.44
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.2.1
  - pip=23.3.2
  - pixman=0.46.0
  - prompt-toolkit=3.0.51
  - prompt_toolkit=3.0.51
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pybind11=2.13.6
  - pybind11-global=2.13.6
  - pygments=2.19.1
  - pyparsing=3.2.3
  - pyside6=6.9.0
  - python=3.10.17
  - python-tzdata=2025.2
  - python_abi=3.10
  - pytorch=2.6.0
  - pytz=2025.2
  - pywavelets=1.8.0
  - qhull=2020.2
  - qt6-main=6.9.0
  - rav1e=0.7.1
  - readline=8.2
  - scikit-image=0.25.2
  - scipy=1.15.2
  - setuptools=75.8.2
  - six=1.17.0
  - sleef=3.8
  - snappy=1.2.1
  - stack_data=0.6.3
  - svt-av1=3.0.2
  - sympy=1.14.0
  - tbb=2021.13.0
  - threadpoolctl=3.6.0
  - tifffile=2025.5.10
  - tk=8.6.13
  - torchvision=0.21.0
  - torchvision-extra-decoders=0.0.2
  - tornado=6.5
  - tqdm=4.67.1
  - traitlets=5.14.3
  - tzdata=2025b
  - unicodedata2=16.0.0
  - wayland=1.23.1
  - wcwidth=0.2.13
  - wheel=0.45.1
  - x265=3.5
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.44
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - zfp=1.0.1
  - zlib-ng=2.2.4
  - zstd=1.5.7
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.10.11
      - aiosignal==1.3.2
      - anyio==4.9.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - boltons==25.0.0
      - cattrs==24.1.3
      - certifi==2025.4.26
      - cffi==1.17.1
      - click==8.1.8
      - cluster-tools==2.3.5
      - frozenlist==1.6.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.27.2
      - idna==3.10
      - loxun==2.0
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - ml-dtypes==0.5.1
      - multidict==6.4.3
      - natsort==8.4.0
      - numpy==2.2.5
      - pims==0.7
      - propcache==0.3.1
      - psutil==6.0.0
      - pycparser==2.22
      - pynndescent==0.5.13
      - python-dateutil==2.8.2
      - python-dotenv==1.0.1
      - rich==13.8.1
      - scikit-learn==1.6.1
      - shellingham==1.5.4
      - slicerator==1.1.0
      - sniffio==1.3.1
      - tensorstore==0.1.75
      - typer==0.12.5
      - typing-extensions==4.12.2
      - universal-pathlib==0.2.6
      - webknossos==2.3.5
      - wget==3.2
      - wkw==1.1.24
      - yarl==1.20.0
      - zipp==3.5.1
