name: synapse_minimal
channels:
  - defaults
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.9
  - numpy=1.23.*
  - pandas=1.5.*
  - pytorch
  - torchvision
  - matplotlib
  - scikit-learn
  - scikit-image
  - scipy
  - tqdm
  - pillow
  - h5py
  - umap-learn
  - pip
  
  - pip:
    - plotly
    - tensorboard 
    - seaborn 
    - imageio
    - webknossos

# conda env create -f environment_minimal.yml
# conda activate synapse_minimal 