name: synapse_environment
channels:
  - defaults
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - numpy=1.23.5
  - pandas=1.5.3
  - pytorch=2.7.0
  - torchvision=0.22.0
  # - matplotlib=3.8.2
  - scikit-learn=1.3.2
  - scikit-image=0.25.2
  - scipy=1.15.3
  - tqdm=4.67.1
  - pillow=11.2.1
  - h5py=3.13.0
  # - umap-learn=0.5.7
  - ipython=8.17.2
  - joblib=1.5.0
  - numba=0.61.2
  - networkx=3.2.1
  - imageio=2.37.0
  # - seaborn=0.13.2
  # - plotly=6.0.1
  - pip=23.3.2
  
  - pip:
    # - tensorboard==2.15.1
    - webknossos==2.3.5
    # - cluster_tools==2.3.5
    - wkw==1.1.24
    - wget==3.2
    - PIMS==0.7
    - pynndescent==0.5.13

# To create and activate the environment:
# conda env create -f environment.yaml
# conda activate synapse_environment 